spring.application.name=jobconnect
# App Info
server.port=8080

# JSON Settings
spring.jackson.default-property-inclusion=non_null
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Kolkata

# Logging
logging.level.root=INFO
logging.level.com.jobportal=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{20} - %msg%n

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:4200

# Custom
app.name=JobConnect
app.version=1.0.0